{{ if and (include "install-operator" .) (empty (include "exists-linkerd-namespace" .)) -}}
kind: Namespace
apiVersion: v1
# avoided label `app.kubernetes.io/part-of` so that the CLI undelete subcommand doesn't delete it
metadata:
  name: {{ .Values.linkerd.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
{{ end -}}
