{{ if (include "install-operator" .) -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controlplanes.linkerd.buoyant.io
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
spec:
  group: linkerd.buoyant.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [components]
            properties:
              components:
                type: object
                properties:
                  linkerd:
                    type: object
                    properties:
                      version:
                        type: string
                      controlPlaneConfig:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                  linkerdJaeger:
                    type: object
                    properties:
                      version:
                        type: string
                      config:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              status:
                type: string
              desired:
                type: string
              current:
                type: string
              lastUpdateAttempt:
                type: string
              lastUpdateAttemptResult:
                type: string
              lastUpdateAttemptMessage:
                type: string
    additionalPrinterColumns:
    - name: Status
      type: string
      description: The status of the controlplane.
      jsonPath: .status.status
    - name: Desired
      type: string
      description: The desired version of the core control plane.
      jsonPath: .status.desired
    - name: Current
      type: string
      description: The current version of the core control plane.
      jsonPath: .status.current
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Cluster
  names:
    plural: controlplanes
    singular: controlplane
    kind: ControlPlane
{{ end -}}
