{{ if (include "install-operator" .) -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-control-plane-operator
  {{- if eq .Release.Service "Buoyant Cloud" }}
  namespace: {{.Release.Namespace}}
  {{- end }}
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    app.kubernetes.io/component: linkerd-control-plane-operator
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
{{ end -}}
