{{ if and (include "install-operator" .) .Values.controlPlaneOperator.extendedRBAC.enabled -}}
{{- /* Sync with operator/pkg/migrations/migrator/rule.go */}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-control-plane-operator-extended-helm
  namespace: {{.Values.controlPlaneOperator.extendedRBAC.helmSecretNamespace}}
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    app.kubernetes.io/component: linkerd-control-plane-operator
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create", "delete"]
{{ end -}}
