{{ if (include "install-operator" .) -}}
# Allows the operator to update resources in the Linkerd namespace
{{- /* Sync with operator/pkg/migrations/migrator/rule.go */}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-control-plane-operator-linkerd
  namespace: {{.Values.linkerd.namespace}}
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    app.kubernetes.io/component: linkerd-control-plane-operator
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "services", "serviceaccounts"]
  verbs: ["get", "list", "watch", "update", "create", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "update", "patch", "delete", "create"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "update", "patch", "create"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]
- apiGroups: ["policy", "extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
{{ end -}}
