{{ if (include "install-operator" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-data-plane-operator
  {{- if eq .Release.Service "Buoyant Cloud" }}
  namespace: {{.Release.Namespace}}
  {{- end }}
  annotations:
    buoyant.cloud/version: v{{.Chart.Version | replace "+" "_"}}
  labels:
    app.kubernetes.io/version: v{{.Chart.Version | replace "+" "_"}}
    app.kubernetes.io/part-of: buoyant-cloud
    app.kubernetes.io/component: linkerd-data-plane-operator
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
    linkerd.io/extension: buoyant
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: buoyant-cloud
      app.kubernetes.io/component: linkerd-data-plane-operator
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        {{- with .Values.podAnnotations }}{{ toYaml . | trim | nindent 8 }}{{- end }}
      labels:
        app.kubernetes.io/part-of: buoyant-cloud
        app.kubernetes.io/component: linkerd-data-plane-operator
        {{- with .Values.podLabels}}{{ toYaml . | trim | nindent 8 }}{{- end }}
    spec:
      containers:
      - args:
        - dataplane
        - "-api-addr={{ .Values.api.apiAddress }}"
        {{- if .Values.dataPlaneOperator.noTLS }}
        - "-no-tls"
        {{- end }}
        - -log-level={{.Values.dataPlaneOperator.logLevel}}
        env:
        - name: BUOYANT_CLOUD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: buoyant-cloud-org-credentials
        - name: BUOYANT_CLOUD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: buoyant-cloud-org-credentials
        - name: LICENSE
          value: {{.Values.license | default "" | quote}}
        - name: ENVIRONMENT
          {{- /* Not exposed in the default values.yaml */}}
          value: {{.Values.environment | default "prod"}}
        - name: NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: "{{ .Values.global.azure.images.agent.registry }}/{{ .Values.global.azure.images.agent.image }}@{{ .Values.global.azure.images.agent.digest }}"
        name: linkerd-data-plane-operator
        ports:
        - name: admin
          containerPort: 9993
        livenessProbe:
          httpGet:
            path: /ping
            port: 9993
        readinessProbe:
          httpGet:
            path: /ready
            port: 9993
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
      securityContext:
        fsGroup: 65534
      serviceAccountName: linkerd-data-plane-operator
{{ end -}}
