{{ if (include "install-operator" .) -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dataplanes.linkerd.buoyant.io
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
spec:
  group: linkerd.buoyant.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - workloadSelector
            properties:
              workloadSelector:
                type: object
                description: Selects workloads to rollout. Selects all if empty.
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              status:
                type: string
              desired:
                type: integer
              current:
                type: integer
              lastUpdateAttempt:
                type: string
              lastUpdateAttemptResult:
                type: string
              lastUpdateAttemptMessage:
                type: string
    additionalPrinterColumns:
    - name: Status
      type: string
      description: The status of the dataplane.
      jsonPath: .status.status
    - name: Desired
      type: string
      description: The desired number of up-to-date workloads.
      jsonPath: .status.desired
    - name: Current
      type: string
      description: The current number of up-to-date workloads.
      jsonPath: .status.current
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: dataplanes
    singular: dataplane
    kind: DataPlane
{{ end -}}
