{{ if .Values.enablePSP -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-metadata-psp
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
rules:
- apiGroups: ['policy', 'extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - buoyant-operator-namespace-metadata
{{ end -}}
