{{ if .Values.enablePSP -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-metadata-psp
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    helm.sh/chart: {{.Chart.Name}}-v{{.Chart.Version | replace "+" "_"}}
roleRef:
  kind: Role
  name: namespace-metadata-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: namespace-metadata
  namespace: {{.Release.Namespace}}
{{ end -}}
