## Added for Azure K8S Apps
global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      agent:
        # tag: stable-2.12.2
        digest: sha256:680d5557ccacd3536d6b30297f293f292e49822007868e93b02fdeecccc1c18c
        image: linkerd-buoyant
        registry: ghcr.io/buoyantio/
      metrics:
        digest: sha256:44198d3143d7e66ea318c09f9de6d69143a2f90069adb6e1f6cc133697470004
        image: metrics-agent:v0.29.0
        registry: ghcr.io/buoyantio/
      bash:
        digest: sha256:2d4fbf1ca5d2b949f6263a1a10bd4a5813eb385418c186681c21839d85491601
        image: bash:4.0.44
        registry: ghcr.io/buoyantio/
      curl:
        digest: sha256:d588ff348c251f8e4d1b2053125c34d719a98ff3ef20895c49684b3743995073
        image: curl
        registry: ghcr.io/buoyantio/
##

agent:
  # -- API address for Buoyant Cloud
  apiAddress: api.buoyant.cloud:443

  # -- image of the buoyant-cloud-agent pod
  image: ghcr.io/buoyantio/linkerd-buoyant

  # -- imageVersion of the buoyant-cloud-agent pod
  imageVersion:

  # -- Disable TLS. Only use for testing.
  noTLS: false

  # -- Log level for the buoyant-cloud-agent pod
  logLevel: info

metrics:
  # -- API address for Buoyant Cloud
  apiAddress: api.buoyant.cloud:443

  # -- Disable TLS. Only use for testing.
  noTLS: false

  # -- Log level for the buoyant-cloud-metrics pod
  logLevel: info

metadata:
  # -- The ID for this agent
  agentID:

  # -- The name for this agent. Required.
  agentName:

api:
  # -- The client id. Required, unless a buoyant-cloud-org-credentials secret
  # already exists in the release namespace.
  clientID:

  # -- The client secret. Required, unless a buoyant-cloud-org-credentials
  # secret already exists in the release namespace.
  clientSecret:

  # -- API address for Buoyant Cloud
  apiAddress: api.buoyant.cloud:443

  # -- Disable TLS. Only use for testing.
  noTLS: false

# -- Enable fully managed Linkerd.
managed: true

# -- License file contents; only use if you were provided with a license file,
# otherwise it'll be retrieved automatically
license:

linkerd:
  # -- Namespace to install Linkerd, or namespace of existing Linkerd instance to manage
  namespace: linkerd

linkerdJaeger:
  # -- Set to true to manage the linkerd-jaeger extension
  enabled: false
  # -- Namespace of existing linkerd-jaeger instance to manage
  namespace: linkerd-jaeger

dataPlaneOperator:
  # -- image of the linkerd-data-plane-operator pod.
  image: ghcr.io/buoyantio/linkerd-buoyant

  # -- imageVersion of the linkerd-data-plane-operator pod.
  imageVersion:

  # -- Log level for the the linkerd-data-plane-operator pod.
  logLevel: info

  # -- Disable TLS. Only use for testing.
  noTLS: false

controlPlaneOperator:
  extendedRBAC:
    # -- Add the linkerd-control-plane-operator-extended ClusterRole providing extra RBAC
    # required for upgrading Linkerd Helm installations from versions
    # stable-2.10 and stable-2.11
    enabled: true

    # -- Namespace used to install the old Linkerd2 Helm chart config secret in
    # versions stable-2.10 and stable-2.11
    helmSecretNamespace: default

  # -- Helm release name used to install the old linkerd2 Helm chart in
  # versions stable-2.10 and stable-2.11.
  helmReleaseName: linkerd2

  # -- image of the linkerd-control-plane-operator pod.
  image: ghcr.io/buoyantio/linkerd-buoyant

  # -- imageVersion of the linkerd-control-plane-operator pod.
  imageVersion:

  # -- Log level for the the linkerd-control-plane-operator pod.
  logLevel: info

  # -- Disable TLS. Only use for testing.
  noTLS: false

# -- Create a PSP resource and bind it to the linkerd-data-plane-operator and
# linkerd-control-plane-operator SAs. Note PSP has been deprecated since k8s
# v1.21.
enablePSP: false

# -- Additional annotations to add to all pods
podAnnotations: {}

# -- Additional labels to add to all pods
podLabels: {}
